name: Publish Python Development Distribution to PyPI

on:
  push:
    branches:
      - develop  # Trigger on pushes to develop branch

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Latest Tag
        id: get-latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1.6.0
        with:
          semver_only: true
          with_initial_version: false
      - name: Code vs Releases Version Check
        id: release-info
        run: |
          RELEASE_VERSION=$(echo $LATEST_RELEASE | tr -d "v ")
          VERSION=$(cat diplomat/__init__.py | grep "__version__" | cut -d "=" -f 2 | tr -d '" ')
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
            then
              echo "$VERSION is not a valid version!"
              exit 1
          fi
          PROPOSED_TAG="v${VERSION}-dev"  # Append -dev for development builds
          echo "Python package version: $VERSION"
          echo "Github release version: $RELEASE_VERSION"
          echo "Next proposed tag: $PROPOSED_TAG"
          echo "PYTHON_VERSION=$VERSION" >> "$GITHUB_OUTPUT"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
          echo "NEXT_TAG=$PROPOSED_TAG" >> "$GITHUB_OUTPUT"
        env:
          LATEST_RELEASE: ${{ steps.get-latest-tag.outputs.tag }}
    outputs:
      RELEASE_VERSION: ${{ steps.release-info.outputs.RELEASE_VERSION }}
      PYTHON_VERSION: ${{ steps.release-info.outputs.PYTHON_VERSION }}
      NEXT_TAG: ${{ steps.release-info.outputs.NEXT_TAG }}

  # Build, Publish and GitHub Release steps remain mostly the same, except for some nuances.
  # Here's a quick change for the publish-to-pypi job:

  publish-to-pypi:
    name: Publish Python development distribution to PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi-test  # Use a different environment or adjust as necessary
      url: https://test.pypi.org/p/diplomat-track
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__  # Ensure this is set or use secrets.PYPI_API_TOKEN
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}  # Use a token for test.pypi.org
          repository_url: https://test.pypi.org/legacy/  # Publish to test PyPI for development versions
          skip-existing: true
